//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HBS
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IHBSTransformableDatabaseView"/> reusable schema assigned.
	/// </summary>
	public interface IHBSTransformableDatabaseView
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "HBSTransformableDatabaseView";


		/// <summary>
		/// TransformableDatabaseViewDisplayName.
		/// </summary>
		public string TransformableDatabaseViewDisplayName { get; set; }


		/// <summary>
		/// TransformableDatabaseViewCodeName.
		/// </summary>
		public string TransformableDatabaseViewCodeName { get; set; }


		/// <summary>
		/// TransformableDatabaseViewEditor.
		/// </summary>
		public string TransformableDatabaseViewEditor { get; set; }
	}
}