//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace HBS
{
	/// <summary>
	/// Represents a content item of type <see cref="TransformableDatabaseContentView"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class TransformableDatabaseContentView : IContentItemFieldsSource, IHBSTransformableDatabaseView
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "HBS.TransformableDatabaseContentView";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// TransformableDatabaseViewContentType.
		/// </summary>
		public IEnumerable<string> TransformableDatabaseViewContentType { get; set; }


		/// <summary>
		/// TransformableDatabaseViewDisplayName.
		/// </summary>
		public string TransformableDatabaseViewDisplayName { get; set; }


		/// <summary>
		/// TransformableDatabaseViewCodeName.
		/// </summary>
		public string TransformableDatabaseViewCodeName { get; set; }


		/// <summary>
		/// TransformableDatabaseViewEditor.
		/// </summary>
		public string TransformableDatabaseViewEditor { get; set; }
	}
}